<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>1.3.0</Version>
    <RootNamespace>Pathoschild.Stardew.CentralStation</RootNamespace>

    <IgnoreModFilePaths>assets/.paths.png, assets/.spring_outdoorsTileSheet.png, assets/.spring_outdoorsTileSheet2.png, assets/.spring_Shadows.png</IgnoreModFilePaths>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" />
  </ItemGroup>

  <ItemGroup>
    <ContentPacks Include="[CP] CentralStation" Version="$(Version)" />
  </ItemGroup>

  <Import Project="..\Common\Common.projitems" Label="Shared" />
</Project>
