name: "Upload Release Zips"
description: "Upload the produced mod release zips as artifacts on the current build, with one artifact per mod."

inputs:
    path:
        description: "The path to the folder containing release zips."
        required: false
        default: "_releases"

runs:
    using: "composite"
    steps:
        - name: Install artifact client
          uses: lhotari/gh-actions-artifact-client@v2

        - name: Upload artifacts
          shell: pwsh
          run: |
              foreach ($file in (Get-ChildItem -Path "${{inputs.path}}" -Filter "*.zip")) {
                  Get-Content $file.FullName -AsByteStream | gh-actions-artifact-client.js upload $file.BaseName
              }
