name: Build releases

on:
    push:
        branches:
            - develop
            - stable
            - build-test

jobs:
    build:
        permissions:
           id-token: write     # for attestation
           attestations: write # for attestation

        runs-on: ubuntu-latest
        steps:
            - name: Fetch code
              uses: actions/checkout@v4
              with:
                  fetch-tags: false

            - name: Fetch reference assemblies
              uses: ./.github/actions/add-reference-assemblies

            - name: Set prerelease versions
              if: github.ref != 'refs/heads/stable'
              uses: ./.github/actions/set-prerelease-versions

            - name: Install .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 6.0.x

            - name: Build mods
              run: dotnet build

            - name: Run tests
              run: dotnet test --no-build

            - name: Upload release zips
              uses: ./.github/actions/upload-release-artifacts

            - name: Generate artifact attestations
              if: github.ref == 'refs/heads/stable'
              uses: actions/attest-build-provenance@v2
              with:
                  subject-path: _releases/*.zip
