name: Build releases
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
           id-token: write     # for attestation
           attestations: write # for attestation
        env:
            IS_RELEASE: ${{ github.ref == 'refs/heads/stable' }}
            IS_ALPHA: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/build-test' }}

        steps:
            - name: Fetch code
              uses: actions/checkout@v4
              with:
                  fetch-tags: false

            - name: Fetch reference assemblies
              uses: ./.github/actions/add-reference-assemblies

            - name: Set prerelease versions
              uses: ./.github/actions/set-prerelease-versions
              if: env.IS_ALPHA

            - name: Install .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 6.0.x

            - name: Build mods
              run: dotnet build

            - name: Run tests
              run: dotnet test --no-build

            - name: Upload release zips
              uses: ./.github/actions/upload-release-artifacts
              if: env.IS_RELEASE || env.IS_ALPHA

            - name: Generate artifact attestations
              if: env.IS_RELEASE
              uses: actions/attest-build-provenance@v2
              with:
                  subject-path: _releases/*.zip
